name = "SugarBLAS"
uuid = "0999239e-cb9f-5507-94be-17f19fa7f34d"
authors = ["Juan Antonio López Mendoza <juanlopezm94@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
